language: rust
cache: cargo

rust:
  - stable
  - nightly

script:
  - cargo test --all --release
  - cargo test --all --all-features --release
  - cargo test --all --all-features --release -- --ignored
  - ./test_aesni.sh

env:
  - RUSTFLAGS="-D warnings"

matrix:
  allow_failures:
    - name: rustfmt
    - name: clippy
    - rust: nightly
  fast_finish: true
  include:
    - name: "Rust: 1.32.0"
      rust: 1.32.0
      script: ./test_aesni.sh

    # chacha20 crate with SSE2 and AVX2 backends
    - name: "Rust: stable (chacha20)"
      rust: stable
      script:
        - RUSTFLAGS="-Ctarget-feature=+sse2" cargo test --package chacha20 --release
        - RUSTFLAGS="-Ctarget-feature=+avx2" cargo test --package chacha20 --release
        - cd chacha20 && cargo build --no-default-features --features=rng # ensure RNG-only build works

    # no_std build
    - name: "Rust: 1.34.0 (thumbv7em-none-eabihf)"
      rust: 1.34.0
      install: rustup target add thumbv7em-none-eabihf
      script: cargo build --all --target thumbv7em-none-eabihf --release
    - name: "Rust: stable (thumbv7em-none-eabihf)"
      rust: stable
      install: rustup target add thumbv7em-none-eabihf
      script: cargo build --all --target thumbv7em-none-eabihf --release

    - name: rustfmt
      rust: stable
      install: rustup component add rustfmt
      script: cargo fmt --all -- --check
    - name: clippy
      rust: stable
      install: rustup component add clippy
      script: cargo clippy --all

branches:
  only:
    - master
