[package]
name = "ctr"
version = "0.5.0"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "CTR block mode of operation"
documentation = "https://docs.rs/ctr"
repository = "https://github.com/RustCrypto/stream-ciphers"
keywords = ["crypto", "stream-cipher", "trait"]
categories = ["cryptography", "no-std"]
readme = "README.md"
edition = "2018"

[dependencies]
stream-cipher = { version = "0.6", features = ["block-cipher"] }

[dev-dependencies]
aes = "0.5"
stream-cipher = { version = "0.6", features = ["dev"] }
